### PR TITLE
0.2.0

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by bencharp** [comment]
!testme

**Comment by bencharp** [comment]
@ericgaspar my local tests return a `502 bad gateway` error.

It seems that there is a problem related to the access rights of the certificates and/or that we need to adapt the `https` configuration of the `server.js`  :

see readme : [armadietto#serving-over-https](https://github.com/remotestorage/armadietto#serving-over-https)

>  ...So you can have an SSL-terminating proxy in front of armadietto as long as it sets one of those headers, and does not let external clients set them. In this setup, you can set https.force = true but omit https.port; this means armadietto itself will not accept encrypted connections but will apply the above behaviour to enforce secure connections.



As I still have a lot of weaknesses in this domain, some confirmations / explanations / solutions  would be welcome :slightly_smiling_face:

**Review by bencharp — CHANGES_REQUESTED** [review]
see my comment above

**Pull request closed without merging**
